package com.example.springLoan.enums;

public enum SettingName {
    MIN_TERM, MAX_TERM, MIN_AMOUNT, MAX_AMOUNT, MIN_REJECTION_TIME, MAX_REJECTION_TIME, DUE_DATE, AMOUNT,
    APPLICATION_DATE, EXTENSION_TERM, AMOUNT_TO_PAY, RATE_OF_INTEREST, TERM
}
